version: '3.8'
services:
  db:
    build: .  # Builds from the Dockerfile in the current directory
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mydb 